// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/mclgui.proto

package __

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GuiServerClient is the client API for GuiServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GuiServerClient interface {
	LogQSO(ctx context.Context, in *QSOMessage, opts ...grpc.CallOption) (*QSO, error)
	GetActiveQSOs(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SnapshotMessage, error)
	DeleteQSO(ctx context.Context, in *QSO, opts ...grpc.CallOption) (*StandardResponse, error)
	GetScore(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ScoreResponse, error)
}

type guiServerClient struct {
	cc grpc.ClientConnInterface
}

func NewGuiServerClient(cc grpc.ClientConnInterface) GuiServerClient {
	return &guiServerClient{cc}
}

func (c *guiServerClient) LogQSO(ctx context.Context, in *QSOMessage, opts ...grpc.CallOption) (*QSO, error) {
	out := new(QSO)
	err := c.cc.Invoke(ctx, "/mcl.GuiServer/LogQSO", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guiServerClient) GetActiveQSOs(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SnapshotMessage, error) {
	out := new(SnapshotMessage)
	err := c.cc.Invoke(ctx, "/mcl.GuiServer/GetActiveQSOs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guiServerClient) DeleteQSO(ctx context.Context, in *QSO, opts ...grpc.CallOption) (*StandardResponse, error) {
	out := new(StandardResponse)
	err := c.cc.Invoke(ctx, "/mcl.GuiServer/DeleteQSO", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guiServerClient) GetScore(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ScoreResponse, error) {
	out := new(ScoreResponse)
	err := c.cc.Invoke(ctx, "/mcl.GuiServer/GetScore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuiServerServer is the server API for GuiServer service.
// All implementations must embed UnimplementedGuiServerServer
// for forward compatibility
type GuiServerServer interface {
	LogQSO(context.Context, *QSOMessage) (*QSO, error)
	GetActiveQSOs(context.Context, *empty.Empty) (*SnapshotMessage, error)
	DeleteQSO(context.Context, *QSO) (*StandardResponse, error)
	GetScore(context.Context, *empty.Empty) (*ScoreResponse, error)
	mustEmbedUnimplementedGuiServerServer()
}

// UnimplementedGuiServerServer must be embedded to have forward compatible implementations.
type UnimplementedGuiServerServer struct {
}

func (UnimplementedGuiServerServer) LogQSO(context.Context, *QSOMessage) (*QSO, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogQSO not implemented")
}
func (UnimplementedGuiServerServer) GetActiveQSOs(context.Context, *empty.Empty) (*SnapshotMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveQSOs not implemented")
}
func (UnimplementedGuiServerServer) DeleteQSO(context.Context, *QSO) (*StandardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteQSO not implemented")
}
func (UnimplementedGuiServerServer) GetScore(context.Context, *empty.Empty) (*ScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScore not implemented")
}
func (UnimplementedGuiServerServer) mustEmbedUnimplementedGuiServerServer() {}

// UnsafeGuiServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuiServerServer will
// result in compilation errors.
type UnsafeGuiServerServer interface {
	mustEmbedUnimplementedGuiServerServer()
}

func RegisterGuiServerServer(s grpc.ServiceRegistrar, srv GuiServerServer) {
	s.RegisterService(&GuiServer_ServiceDesc, srv)
}

func _GuiServer_LogQSO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QSOMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuiServerServer).LogQSO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mcl.GuiServer/LogQSO",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuiServerServer).LogQSO(ctx, req.(*QSOMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuiServer_GetActiveQSOs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuiServerServer).GetActiveQSOs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mcl.GuiServer/GetActiveQSOs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuiServerServer).GetActiveQSOs(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuiServer_DeleteQSO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QSO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuiServerServer).DeleteQSO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mcl.GuiServer/DeleteQSO",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuiServerServer).DeleteQSO(ctx, req.(*QSO))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuiServer_GetScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuiServerServer).GetScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mcl.GuiServer/GetScore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuiServerServer).GetScore(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// GuiServer_ServiceDesc is the grpc.ServiceDesc for GuiServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GuiServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mcl.GuiServer",
	HandlerType: (*GuiServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogQSO",
			Handler:    _GuiServer_LogQSO_Handler,
		},
		{
			MethodName: "GetActiveQSOs",
			Handler:    _GuiServer_GetActiveQSOs_Handler,
		},
		{
			MethodName: "DeleteQSO",
			Handler:    _GuiServer_DeleteQSO_Handler,
		},
		{
			MethodName: "GetScore",
			Handler:    _GuiServer_GetScore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mclgui.proto",
}

// RealtimeGuiServerClient is the client API for RealtimeGuiServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RealtimeGuiServerClient interface {
	// Prepares a QSO, used to generate default QSO content for a specific DX
	// station. e.g. The server will generate exchange message to be sent (like
	// serial number) and expected message from the DX station (like zone)
	DraftQSO(ctx context.Context, in *DraftQSOMessage, opts ...grpc.CallOption) (*QSOMessage, error)
	// Retrieves raw binlog messages from the backend.
	RetrieveQSOUpdates(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (RealtimeGuiServer_RetrieveQSOUpdatesClient, error)
	// Connects to and waiting for cooked spots.
	RetrieveTelnet(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (RealtimeGuiServer_RetrieveTelnetClient, error)
	SendSpotToTelnet(ctx context.Context, in *Spot, opts ...grpc.CallOption) (*StandardResponse, error)
}

type realtimeGuiServerClient struct {
	cc grpc.ClientConnInterface
}

func NewRealtimeGuiServerClient(cc grpc.ClientConnInterface) RealtimeGuiServerClient {
	return &realtimeGuiServerClient{cc}
}

func (c *realtimeGuiServerClient) DraftQSO(ctx context.Context, in *DraftQSOMessage, opts ...grpc.CallOption) (*QSOMessage, error) {
	out := new(QSOMessage)
	err := c.cc.Invoke(ctx, "/mcl.RealtimeGuiServer/DraftQSO", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *realtimeGuiServerClient) RetrieveQSOUpdates(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (RealtimeGuiServer_RetrieveQSOUpdatesClient, error) {
	stream, err := c.cc.NewStream(ctx, &RealtimeGuiServer_ServiceDesc.Streams[0], "/mcl.RealtimeGuiServer/RetrieveQSOUpdates", opts...)
	if err != nil {
		return nil, err
	}
	x := &realtimeGuiServerRetrieveQSOUpdatesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RealtimeGuiServer_RetrieveQSOUpdatesClient interface {
	Recv() (*BinlogMessage, error)
	grpc.ClientStream
}

type realtimeGuiServerRetrieveQSOUpdatesClient struct {
	grpc.ClientStream
}

func (x *realtimeGuiServerRetrieveQSOUpdatesClient) Recv() (*BinlogMessage, error) {
	m := new(BinlogMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *realtimeGuiServerClient) RetrieveTelnet(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (RealtimeGuiServer_RetrieveTelnetClient, error) {
	stream, err := c.cc.NewStream(ctx, &RealtimeGuiServer_ServiceDesc.Streams[1], "/mcl.RealtimeGuiServer/RetrieveTelnet", opts...)
	if err != nil {
		return nil, err
	}
	x := &realtimeGuiServerRetrieveTelnetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RealtimeGuiServer_RetrieveTelnetClient interface {
	Recv() (*Spot, error)
	grpc.ClientStream
}

type realtimeGuiServerRetrieveTelnetClient struct {
	grpc.ClientStream
}

func (x *realtimeGuiServerRetrieveTelnetClient) Recv() (*Spot, error) {
	m := new(Spot)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *realtimeGuiServerClient) SendSpotToTelnet(ctx context.Context, in *Spot, opts ...grpc.CallOption) (*StandardResponse, error) {
	out := new(StandardResponse)
	err := c.cc.Invoke(ctx, "/mcl.RealtimeGuiServer/SendSpotToTelnet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RealtimeGuiServerServer is the server API for RealtimeGuiServer service.
// All implementations must embed UnimplementedRealtimeGuiServerServer
// for forward compatibility
type RealtimeGuiServerServer interface {
	// Prepares a QSO, used to generate default QSO content for a specific DX
	// station. e.g. The server will generate exchange message to be sent (like
	// serial number) and expected message from the DX station (like zone)
	DraftQSO(context.Context, *DraftQSOMessage) (*QSOMessage, error)
	// Retrieves raw binlog messages from the backend.
	RetrieveQSOUpdates(*empty.Empty, RealtimeGuiServer_RetrieveQSOUpdatesServer) error
	// Connects to and waiting for cooked spots.
	RetrieveTelnet(*empty.Empty, RealtimeGuiServer_RetrieveTelnetServer) error
	SendSpotToTelnet(context.Context, *Spot) (*StandardResponse, error)
	mustEmbedUnimplementedRealtimeGuiServerServer()
}

// UnimplementedRealtimeGuiServerServer must be embedded to have forward compatible implementations.
type UnimplementedRealtimeGuiServerServer struct {
}

func (UnimplementedRealtimeGuiServerServer) DraftQSO(context.Context, *DraftQSOMessage) (*QSOMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DraftQSO not implemented")
}
func (UnimplementedRealtimeGuiServerServer) RetrieveQSOUpdates(*empty.Empty, RealtimeGuiServer_RetrieveQSOUpdatesServer) error {
	return status.Errorf(codes.Unimplemented, "method RetrieveQSOUpdates not implemented")
}
func (UnimplementedRealtimeGuiServerServer) RetrieveTelnet(*empty.Empty, RealtimeGuiServer_RetrieveTelnetServer) error {
	return status.Errorf(codes.Unimplemented, "method RetrieveTelnet not implemented")
}
func (UnimplementedRealtimeGuiServerServer) SendSpotToTelnet(context.Context, *Spot) (*StandardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSpotToTelnet not implemented")
}
func (UnimplementedRealtimeGuiServerServer) mustEmbedUnimplementedRealtimeGuiServerServer() {}

// UnsafeRealtimeGuiServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RealtimeGuiServerServer will
// result in compilation errors.
type UnsafeRealtimeGuiServerServer interface {
	mustEmbedUnimplementedRealtimeGuiServerServer()
}

func RegisterRealtimeGuiServerServer(s grpc.ServiceRegistrar, srv RealtimeGuiServerServer) {
	s.RegisterService(&RealtimeGuiServer_ServiceDesc, srv)
}

func _RealtimeGuiServer_DraftQSO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DraftQSOMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealtimeGuiServerServer).DraftQSO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mcl.RealtimeGuiServer/DraftQSO",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealtimeGuiServerServer).DraftQSO(ctx, req.(*DraftQSOMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RealtimeGuiServer_RetrieveQSOUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RealtimeGuiServerServer).RetrieveQSOUpdates(m, &realtimeGuiServerRetrieveQSOUpdatesServer{stream})
}

type RealtimeGuiServer_RetrieveQSOUpdatesServer interface {
	Send(*BinlogMessage) error
	grpc.ServerStream
}

type realtimeGuiServerRetrieveQSOUpdatesServer struct {
	grpc.ServerStream
}

func (x *realtimeGuiServerRetrieveQSOUpdatesServer) Send(m *BinlogMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _RealtimeGuiServer_RetrieveTelnet_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RealtimeGuiServerServer).RetrieveTelnet(m, &realtimeGuiServerRetrieveTelnetServer{stream})
}

type RealtimeGuiServer_RetrieveTelnetServer interface {
	Send(*Spot) error
	grpc.ServerStream
}

type realtimeGuiServerRetrieveTelnetServer struct {
	grpc.ServerStream
}

func (x *realtimeGuiServerRetrieveTelnetServer) Send(m *Spot) error {
	return x.ServerStream.SendMsg(m)
}

func _RealtimeGuiServer_SendSpotToTelnet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Spot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealtimeGuiServerServer).SendSpotToTelnet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mcl.RealtimeGuiServer/SendSpotToTelnet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealtimeGuiServerServer).SendSpotToTelnet(ctx, req.(*Spot))
	}
	return interceptor(ctx, in, info, handler)
}

// RealtimeGuiServer_ServiceDesc is the grpc.ServiceDesc for RealtimeGuiServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RealtimeGuiServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mcl.RealtimeGuiServer",
	HandlerType: (*RealtimeGuiServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DraftQSO",
			Handler:    _RealtimeGuiServer_DraftQSO_Handler,
		},
		{
			MethodName: "SendSpotToTelnet",
			Handler:    _RealtimeGuiServer_SendSpotToTelnet_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RetrieveQSOUpdates",
			Handler:       _RealtimeGuiServer_RetrieveQSOUpdates_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RetrieveTelnet",
			Handler:       _RealtimeGuiServer_RetrieveTelnet_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/mclgui.proto",
}

// RadioServerClient is the client API for RadioServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RadioServerClient interface {
	GetRadioMode(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RadioStatus, error)
	PollRadioMode(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (RadioServer_PollRadioModeClient, error)
	RadioOp(ctx context.Context, in *RadioCommands, opts ...grpc.CallOption) (*StandardResponse, error)
}

type radioServerClient struct {
	cc grpc.ClientConnInterface
}

func NewRadioServerClient(cc grpc.ClientConnInterface) RadioServerClient {
	return &radioServerClient{cc}
}

func (c *radioServerClient) GetRadioMode(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RadioStatus, error) {
	out := new(RadioStatus)
	err := c.cc.Invoke(ctx, "/mcl.RadioServer/GetRadioMode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radioServerClient) PollRadioMode(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (RadioServer_PollRadioModeClient, error) {
	stream, err := c.cc.NewStream(ctx, &RadioServer_ServiceDesc.Streams[0], "/mcl.RadioServer/PollRadioMode", opts...)
	if err != nil {
		return nil, err
	}
	x := &radioServerPollRadioModeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RadioServer_PollRadioModeClient interface {
	Recv() (*RadioStatus, error)
	grpc.ClientStream
}

type radioServerPollRadioModeClient struct {
	grpc.ClientStream
}

func (x *radioServerPollRadioModeClient) Recv() (*RadioStatus, error) {
	m := new(RadioStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *radioServerClient) RadioOp(ctx context.Context, in *RadioCommands, opts ...grpc.CallOption) (*StandardResponse, error) {
	out := new(StandardResponse)
	err := c.cc.Invoke(ctx, "/mcl.RadioServer/RadioOp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RadioServerServer is the server API for RadioServer service.
// All implementations must embed UnimplementedRadioServerServer
// for forward compatibility
type RadioServerServer interface {
	GetRadioMode(context.Context, *empty.Empty) (*RadioStatus, error)
	PollRadioMode(*empty.Empty, RadioServer_PollRadioModeServer) error
	RadioOp(context.Context, *RadioCommands) (*StandardResponse, error)
	mustEmbedUnimplementedRadioServerServer()
}

// UnimplementedRadioServerServer must be embedded to have forward compatible implementations.
type UnimplementedRadioServerServer struct {
}

func (UnimplementedRadioServerServer) GetRadioMode(context.Context, *empty.Empty) (*RadioStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRadioMode not implemented")
}
func (UnimplementedRadioServerServer) PollRadioMode(*empty.Empty, RadioServer_PollRadioModeServer) error {
	return status.Errorf(codes.Unimplemented, "method PollRadioMode not implemented")
}
func (UnimplementedRadioServerServer) RadioOp(context.Context, *RadioCommands) (*StandardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RadioOp not implemented")
}
func (UnimplementedRadioServerServer) mustEmbedUnimplementedRadioServerServer() {}

// UnsafeRadioServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RadioServerServer will
// result in compilation errors.
type UnsafeRadioServerServer interface {
	mustEmbedUnimplementedRadioServerServer()
}

func RegisterRadioServerServer(s grpc.ServiceRegistrar, srv RadioServerServer) {
	s.RegisterService(&RadioServer_ServiceDesc, srv)
}

func _RadioServer_GetRadioMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadioServerServer).GetRadioMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mcl.RadioServer/GetRadioMode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadioServerServer).GetRadioMode(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadioServer_PollRadioMode_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RadioServerServer).PollRadioMode(m, &radioServerPollRadioModeServer{stream})
}

type RadioServer_PollRadioModeServer interface {
	Send(*RadioStatus) error
	grpc.ServerStream
}

type radioServerPollRadioModeServer struct {
	grpc.ServerStream
}

func (x *radioServerPollRadioModeServer) Send(m *RadioStatus) error {
	return x.ServerStream.SendMsg(m)
}

func _RadioServer_RadioOp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RadioCommands)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadioServerServer).RadioOp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mcl.RadioServer/RadioOp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadioServerServer).RadioOp(ctx, req.(*RadioCommands))
	}
	return interceptor(ctx, in, info, handler)
}

// RadioServer_ServiceDesc is the grpc.ServiceDesc for RadioServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RadioServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mcl.RadioServer",
	HandlerType: (*RadioServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRadioMode",
			Handler:    _RadioServer_GetRadioMode_Handler,
		},
		{
			MethodName: "RadioOp",
			Handler:    _RadioServer_RadioOp_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PollRadioMode",
			Handler:       _RadioServer_PollRadioMode_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/mclgui.proto",
}
